### ISSUE TITLE
DICOM to mesh

### ISSUE THREAD

**Issue by yusufalibrahim1994** [drmichaeldouglass/MedBlend#3]
Is there a way to convert the visualized volume render into a mesh in blender that can be exported?

**Comment by drmichaeldouglass** [comment]
Yes. You can use geometry nodes on the CT volume. If you add in a volume to mesh node, it will convert the CT volume to a mesh. You can then apply the geometry nodes modifier. That should save the volume as a mesh object and then you can export that mesh as an OBJ or STL file

**Comment by drmichaeldouglass** [comment]
You can also use the modifier, volume to mesh and select a threshold.
